version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - echo Build enviromment `uname -a` `aws --version 2>&1` node/`node --version` npm/`npm --version`
  build:
    commands:
      - ls
      - serverless deploy | tee deploy.out